<?php

namespace AppBundle\Repository;

/**
 * TextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleItemRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */



}
