<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Article;
use AppBundle\Entity\User;
use AppBundle\Entity\Section;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class ArticleRepository extends \Doctrine\ORM\EntityRepository
{


    /**
     * @return mixed
     */
    public function findPublicOrdered()
    {
        return $this
            ->getEntityManager()
            ->createQuery(
                "SELECT a
                 FROM AppBundle:Article a
                 WHERE a.status = :status
                 AND a.owner = :owner
                 ORDER BY a.section ASC"
            )
            ->setParameter("status", Article::STATUS_PUBLIC)
            ->setParameter("owner", Article::EXPOSE_OWNER_ID)
            ->getResult();
    }

    /**
     * @param User $owner
     * @return mixed
     */
    public function findMyOrdered(User $owner)
    {
        return $this
            ->getEntityManager()
            ->createQuery(
                "SELECT a
                 FROM AppBundle:Article a
                 WHERE a.owner = :owner
                 ORDER BY a.updatedAt ASC"
            )
            ->setParameter("owner", $owner)
            ->getResult();
    }

    /**
     * @param Section $section
     * @return mixed
     */
    public function findArticleBySection(Section $section)
    {
        return $this
            ->getEntityManager()
            ->createQuery(
                "SELECT a
                 FROM AppBundle:Article a
                 WHERE a.section = :section
                 ORDER BY a.updatedAt ASC"
            )
            ->setParameter("section", $section)
            ->getResult();
    }
}
