<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
use AppBundle\Entity\Section;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class SectionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSectionRoute()
    {

        return $this
            ->getEntityManager()
            ->createQuery(
                "SELECT a
                 FROM AppBundle:Section a
                ORDER BY a.id ASC"
            )
            ->getResult();
    }
}
