app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
        resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_bundle_route:
   path:     /ajax_request
   defaults: { _controller: AppBundle:ArticleItem:edit }

